# Example of using LightStep SaaS as the TracingService
# Pretty straightforward, note this is pointing to the LightStep SaaS
# grpc-plain port (8080) and that the access token file is being set

# Note relying on LightStep SaaS is less performant than internally hosted collectors
---
apiVersion: v1
kind: Service
metadata:
  name: lightstep
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: TracingService
      name: tracing
      service: "collector-grpc.lightstep.com:8080"
      driver: lightstep
      config: {
          access_token_file: /config/lightstep_access_token.txt
      }
spec:
  type: ExternalName
  externalName: collector-grpc.lightstep.com

